[2024-08-28 13:42:30,480] {processor.py:153} INFO - Started process (PID=27343) to work on /home/kai/Documents/PROJETOS/twitter_extractor_airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-28 13:42:30,482] {processor.py:641} INFO - Processing file /home/kai/Documents/PROJETOS/twitter_extractor_airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-08-28 13:42:30,483] {logging_mixin.py:115} INFO - [2024-08-28 13:42:30,483] {dagbag.py:507} INFO - Filling up the DagBag from /home/kai/Documents/PROJETOS/twitter_extractor_airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-28 13:42:30,495] {logging_mixin.py:115} INFO - [2024-08-28 13:42:30,495] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/kai/Documents/PROJETOS/twitter_extractor_airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-08-28 13:42:30,495] {logging_mixin.py:115} INFO - [2024-08-28 13:42:30,495] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-08-28 13:42:30,496] {processor.py:653} WARNING - No viable dags retrieved from /home/kai/Documents/PROJETOS/twitter_extractor_airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-28 13:42:30,504] {processor.py:161} INFO - Processing /home/kai/Documents/PROJETOS/twitter_extractor_airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.026 seconds
[2024-08-28 13:43:05,187] {processor.py:153} INFO - Started process (PID=27593) to work on /home/kai/Documents/PROJETOS/twitter_extractor_airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-28 13:43:05,188] {processor.py:641} INFO - Processing file /home/kai/Documents/PROJETOS/twitter_extractor_airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-08-28 13:43:05,189] {logging_mixin.py:115} INFO - [2024-08-28 13:43:05,188] {dagbag.py:507} INFO - Filling up the DagBag from /home/kai/Documents/PROJETOS/twitter_extractor_airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-28 13:43:05,199] {logging_mixin.py:115} INFO - [2024-08-28 13:43:05,199] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/kai/Documents/PROJETOS/twitter_extractor_airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-08-28 13:43:05,199] {logging_mixin.py:115} INFO - [2024-08-28 13:43:05,199] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-08-28 13:43:05,199] {processor.py:653} WARNING - No viable dags retrieved from /home/kai/Documents/PROJETOS/twitter_extractor_airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-28 13:43:05,207] {processor.py:161} INFO - Processing /home/kai/Documents/PROJETOS/twitter_extractor_airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.022 seconds
[2024-08-28 13:43:38,973] {processor.py:153} INFO - Started process (PID=27787) to work on /home/kai/Documents/PROJETOS/twitter_extractor_airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-28 13:43:38,974] {processor.py:641} INFO - Processing file /home/kai/Documents/PROJETOS/twitter_extractor_airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-08-28 13:43:38,974] {logging_mixin.py:115} INFO - [2024-08-28 13:43:38,974] {dagbag.py:507} INFO - Filling up the DagBag from /home/kai/Documents/PROJETOS/twitter_extractor_airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-28 13:43:38,985] {logging_mixin.py:115} INFO - [2024-08-28 13:43:38,985] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/kai/Documents/PROJETOS/twitter_extractor_airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-08-28 13:43:38,985] {logging_mixin.py:115} INFO - [2024-08-28 13:43:38,985] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-08-28 13:43:38,985] {processor.py:653} WARNING - No viable dags retrieved from /home/kai/Documents/PROJETOS/twitter_extractor_airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-28 13:43:38,993] {processor.py:161} INFO - Processing /home/kai/Documents/PROJETOS/twitter_extractor_airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.022 seconds
[2024-08-28 13:44:14,404] {processor.py:153} INFO - Started process (PID=27985) to work on /home/kai/Documents/PROJETOS/twitter_extractor_airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-28 13:44:14,404] {processor.py:641} INFO - Processing file /home/kai/Documents/PROJETOS/twitter_extractor_airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-08-28 13:44:14,405] {logging_mixin.py:115} INFO - [2024-08-28 13:44:14,405] {dagbag.py:507} INFO - Filling up the DagBag from /home/kai/Documents/PROJETOS/twitter_extractor_airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-28 13:44:14,415] {logging_mixin.py:115} INFO - [2024-08-28 13:44:14,415] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/kai/Documents/PROJETOS/twitter_extractor_airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-08-28 13:44:14,415] {logging_mixin.py:115} INFO - [2024-08-28 13:44:14,415] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-08-28 13:44:14,416] {processor.py:653} WARNING - No viable dags retrieved from /home/kai/Documents/PROJETOS/twitter_extractor_airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-28 13:44:14,423] {processor.py:161} INFO - Processing /home/kai/Documents/PROJETOS/twitter_extractor_airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.022 seconds
[2024-08-28 13:44:45,896] {processor.py:153} INFO - Started process (PID=28175) to work on /home/kai/Documents/PROJETOS/twitter_extractor_airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-28 13:44:45,897] {processor.py:641} INFO - Processing file /home/kai/Documents/PROJETOS/twitter_extractor_airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-08-28 13:44:45,898] {logging_mixin.py:115} INFO - [2024-08-28 13:44:45,898] {dagbag.py:507} INFO - Filling up the DagBag from /home/kai/Documents/PROJETOS/twitter_extractor_airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-28 13:44:45,912] {logging_mixin.py:115} INFO - [2024-08-28 13:44:45,912] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/kai/Documents/PROJETOS/twitter_extractor_airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-08-28 13:44:45,912] {logging_mixin.py:115} INFO - [2024-08-28 13:44:45,912] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-08-28 13:44:45,913] {processor.py:653} WARNING - No viable dags retrieved from /home/kai/Documents/PROJETOS/twitter_extractor_airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-28 13:44:45,920] {processor.py:161} INFO - Processing /home/kai/Documents/PROJETOS/twitter_extractor_airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.026 seconds
[2024-08-28 13:45:18,451] {processor.py:153} INFO - Started process (PID=28371) to work on /home/kai/Documents/PROJETOS/twitter_extractor_airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-28 13:45:18,453] {processor.py:641} INFO - Processing file /home/kai/Documents/PROJETOS/twitter_extractor_airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-08-28 13:45:18,454] {logging_mixin.py:115} INFO - [2024-08-28 13:45:18,454] {dagbag.py:507} INFO - Filling up the DagBag from /home/kai/Documents/PROJETOS/twitter_extractor_airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-28 13:45:18,464] {logging_mixin.py:115} INFO - [2024-08-28 13:45:18,464] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/kai/Documents/PROJETOS/twitter_extractor_airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-08-28 13:45:18,464] {logging_mixin.py:115} INFO - [2024-08-28 13:45:18,464] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-08-28 13:45:18,464] {processor.py:653} WARNING - No viable dags retrieved from /home/kai/Documents/PROJETOS/twitter_extractor_airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-28 13:45:18,472] {processor.py:161} INFO - Processing /home/kai/Documents/PROJETOS/twitter_extractor_airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.024 seconds
[2024-08-28 13:45:52,312] {processor.py:153} INFO - Started process (PID=28574) to work on /home/kai/Documents/PROJETOS/twitter_extractor_airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-28 13:45:52,313] {processor.py:641} INFO - Processing file /home/kai/Documents/PROJETOS/twitter_extractor_airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-08-28 13:45:52,313] {logging_mixin.py:115} INFO - [2024-08-28 13:45:52,313] {dagbag.py:507} INFO - Filling up the DagBag from /home/kai/Documents/PROJETOS/twitter_extractor_airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-28 13:45:52,324] {logging_mixin.py:115} INFO - [2024-08-28 13:45:52,323] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/kai/Documents/PROJETOS/twitter_extractor_airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-08-28 13:45:52,324] {logging_mixin.py:115} INFO - [2024-08-28 13:45:52,324] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-08-28 13:45:52,324] {processor.py:653} WARNING - No viable dags retrieved from /home/kai/Documents/PROJETOS/twitter_extractor_airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-28 13:45:52,332] {processor.py:161} INFO - Processing /home/kai/Documents/PROJETOS/twitter_extractor_airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.022 seconds
[2024-08-28 13:46:25,856] {processor.py:153} INFO - Started process (PID=28765) to work on /home/kai/Documents/PROJETOS/twitter_extractor_airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-28 13:46:25,857] {processor.py:641} INFO - Processing file /home/kai/Documents/PROJETOS/twitter_extractor_airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-08-28 13:46:25,857] {logging_mixin.py:115} INFO - [2024-08-28 13:46:25,857] {dagbag.py:507} INFO - Filling up the DagBag from /home/kai/Documents/PROJETOS/twitter_extractor_airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-28 13:46:25,868] {logging_mixin.py:115} INFO - [2024-08-28 13:46:25,868] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/kai/Documents/PROJETOS/twitter_extractor_airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-08-28 13:46:25,868] {logging_mixin.py:115} INFO - [2024-08-28 13:46:25,868] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-08-28 13:46:25,869] {processor.py:653} WARNING - No viable dags retrieved from /home/kai/Documents/PROJETOS/twitter_extractor_airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-28 13:46:25,877] {processor.py:161} INFO - Processing /home/kai/Documents/PROJETOS/twitter_extractor_airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.023 seconds
[2024-08-28 13:47:01,690] {processor.py:153} INFO - Started process (PID=29615) to work on /home/kai/Documents/PROJETOS/twitter_extractor_airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-28 13:47:01,691] {processor.py:641} INFO - Processing file /home/kai/Documents/PROJETOS/twitter_extractor_airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-08-28 13:47:01,692] {logging_mixin.py:115} INFO - [2024-08-28 13:47:01,692] {dagbag.py:507} INFO - Filling up the DagBag from /home/kai/Documents/PROJETOS/twitter_extractor_airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-28 13:47:01,704] {logging_mixin.py:115} INFO - [2024-08-28 13:47:01,703] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/kai/Documents/PROJETOS/twitter_extractor_airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-08-28 13:47:01,704] {logging_mixin.py:115} INFO - [2024-08-28 13:47:01,704] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-08-28 13:47:01,704] {processor.py:653} WARNING - No viable dags retrieved from /home/kai/Documents/PROJETOS/twitter_extractor_airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-28 13:47:01,714] {processor.py:161} INFO - Processing /home/kai/Documents/PROJETOS/twitter_extractor_airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.026 seconds
[2024-08-28 13:47:34,859] {processor.py:153} INFO - Started process (PID=29928) to work on /home/kai/Documents/PROJETOS/twitter_extractor_airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-28 13:47:34,860] {processor.py:641} INFO - Processing file /home/kai/Documents/PROJETOS/twitter_extractor_airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-08-28 13:47:34,860] {logging_mixin.py:115} INFO - [2024-08-28 13:47:34,860] {dagbag.py:507} INFO - Filling up the DagBag from /home/kai/Documents/PROJETOS/twitter_extractor_airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-28 13:47:34,872] {logging_mixin.py:115} INFO - [2024-08-28 13:47:34,871] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/kai/Documents/PROJETOS/twitter_extractor_airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-08-28 13:47:34,872] {logging_mixin.py:115} INFO - [2024-08-28 13:47:34,872] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-08-28 13:47:34,872] {processor.py:653} WARNING - No viable dags retrieved from /home/kai/Documents/PROJETOS/twitter_extractor_airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-28 13:47:34,881] {processor.py:161} INFO - Processing /home/kai/Documents/PROJETOS/twitter_extractor_airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.024 seconds
[2024-08-28 13:48:08,556] {processor.py:153} INFO - Started process (PID=30142) to work on /home/kai/Documents/PROJETOS/twitter_extractor_airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-28 13:48:08,557] {processor.py:641} INFO - Processing file /home/kai/Documents/PROJETOS/twitter_extractor_airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-08-28 13:48:08,558] {logging_mixin.py:115} INFO - [2024-08-28 13:48:08,558] {dagbag.py:507} INFO - Filling up the DagBag from /home/kai/Documents/PROJETOS/twitter_extractor_airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-28 13:48:08,570] {logging_mixin.py:115} INFO - [2024-08-28 13:48:08,570] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/kai/Documents/PROJETOS/twitter_extractor_airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-08-28 13:48:08,570] {logging_mixin.py:115} INFO - [2024-08-28 13:48:08,570] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-08-28 13:48:08,570] {processor.py:653} WARNING - No viable dags retrieved from /home/kai/Documents/PROJETOS/twitter_extractor_airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-28 13:48:08,579] {processor.py:161} INFO - Processing /home/kai/Documents/PROJETOS/twitter_extractor_airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.025 seconds
[2024-08-28 13:48:42,729] {processor.py:153} INFO - Started process (PID=30396) to work on /home/kai/Documents/PROJETOS/twitter_extractor_airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-28 13:48:42,731] {processor.py:641} INFO - Processing file /home/kai/Documents/PROJETOS/twitter_extractor_airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-08-28 13:48:42,732] {logging_mixin.py:115} INFO - [2024-08-28 13:48:42,732] {dagbag.py:507} INFO - Filling up the DagBag from /home/kai/Documents/PROJETOS/twitter_extractor_airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-28 13:48:42,745] {logging_mixin.py:115} INFO - [2024-08-28 13:48:42,744] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/kai/Documents/PROJETOS/twitter_extractor_airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-08-28 13:48:42,745] {logging_mixin.py:115} INFO - [2024-08-28 13:48:42,745] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-08-28 13:48:42,745] {processor.py:653} WARNING - No viable dags retrieved from /home/kai/Documents/PROJETOS/twitter_extractor_airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-28 13:48:42,759] {processor.py:161} INFO - Processing /home/kai/Documents/PROJETOS/twitter_extractor_airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.033 seconds
[2024-08-28 13:49:16,544] {processor.py:153} INFO - Started process (PID=30595) to work on /home/kai/Documents/PROJETOS/twitter_extractor_airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-28 13:49:16,545] {processor.py:641} INFO - Processing file /home/kai/Documents/PROJETOS/twitter_extractor_airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-08-28 13:49:16,545] {logging_mixin.py:115} INFO - [2024-08-28 13:49:16,545] {dagbag.py:507} INFO - Filling up the DagBag from /home/kai/Documents/PROJETOS/twitter_extractor_airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-28 13:49:16,567] {logging_mixin.py:115} INFO - [2024-08-28 13:49:16,566] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/kai/Documents/PROJETOS/twitter_extractor_airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-08-28 13:49:16,567] {logging_mixin.py:115} INFO - [2024-08-28 13:49:16,567] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-08-28 13:49:16,567] {processor.py:653} WARNING - No viable dags retrieved from /home/kai/Documents/PROJETOS/twitter_extractor_airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-28 13:49:16,575] {processor.py:161} INFO - Processing /home/kai/Documents/PROJETOS/twitter_extractor_airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.034 seconds
[2024-08-28 13:49:48,482] {processor.py:153} INFO - Started process (PID=30809) to work on /home/kai/Documents/PROJETOS/twitter_extractor_airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-28 13:49:48,482] {processor.py:641} INFO - Processing file /home/kai/Documents/PROJETOS/twitter_extractor_airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-08-28 13:49:48,483] {logging_mixin.py:115} INFO - [2024-08-28 13:49:48,483] {dagbag.py:507} INFO - Filling up the DagBag from /home/kai/Documents/PROJETOS/twitter_extractor_airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-28 13:49:48,494] {logging_mixin.py:115} INFO - [2024-08-28 13:49:48,494] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/kai/Documents/PROJETOS/twitter_extractor_airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-08-28 13:49:48,494] {logging_mixin.py:115} INFO - [2024-08-28 13:49:48,494] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-08-28 13:49:48,494] {processor.py:653} WARNING - No viable dags retrieved from /home/kai/Documents/PROJETOS/twitter_extractor_airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-28 13:49:48,502] {processor.py:161} INFO - Processing /home/kai/Documents/PROJETOS/twitter_extractor_airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.023 seconds
[2024-08-28 13:50:21,344] {processor.py:153} INFO - Started process (PID=31037) to work on /home/kai/Documents/PROJETOS/twitter_extractor_airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-28 13:50:21,344] {processor.py:641} INFO - Processing file /home/kai/Documents/PROJETOS/twitter_extractor_airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-08-28 13:50:21,345] {logging_mixin.py:115} INFO - [2024-08-28 13:50:21,345] {dagbag.py:507} INFO - Filling up the DagBag from /home/kai/Documents/PROJETOS/twitter_extractor_airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-28 13:50:21,356] {logging_mixin.py:115} INFO - [2024-08-28 13:50:21,356] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/kai/Documents/PROJETOS/twitter_extractor_airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-08-28 13:50:21,356] {logging_mixin.py:115} INFO - [2024-08-28 13:50:21,356] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-08-28 13:50:21,356] {processor.py:653} WARNING - No viable dags retrieved from /home/kai/Documents/PROJETOS/twitter_extractor_airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-28 13:50:21,365] {processor.py:161} INFO - Processing /home/kai/Documents/PROJETOS/twitter_extractor_airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.024 seconds
[2024-08-28 13:50:54,622] {processor.py:153} INFO - Started process (PID=31248) to work on /home/kai/Documents/PROJETOS/twitter_extractor_airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-28 13:50:54,623] {processor.py:641} INFO - Processing file /home/kai/Documents/PROJETOS/twitter_extractor_airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-08-28 13:50:54,624] {logging_mixin.py:115} INFO - [2024-08-28 13:50:54,623] {dagbag.py:507} INFO - Filling up the DagBag from /home/kai/Documents/PROJETOS/twitter_extractor_airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-28 13:50:54,635] {logging_mixin.py:115} INFO - [2024-08-28 13:50:54,635] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/kai/Documents/PROJETOS/twitter_extractor_airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-08-28 13:50:54,635] {logging_mixin.py:115} INFO - [2024-08-28 13:50:54,635] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-08-28 13:50:54,635] {processor.py:653} WARNING - No viable dags retrieved from /home/kai/Documents/PROJETOS/twitter_extractor_airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-28 13:50:54,645] {processor.py:161} INFO - Processing /home/kai/Documents/PROJETOS/twitter_extractor_airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.026 seconds
[2024-08-28 13:51:29,239] {processor.py:153} INFO - Started process (PID=31458) to work on /home/kai/Documents/PROJETOS/twitter_extractor_airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-28 13:51:29,240] {processor.py:641} INFO - Processing file /home/kai/Documents/PROJETOS/twitter_extractor_airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-08-28 13:51:29,241] {logging_mixin.py:115} INFO - [2024-08-28 13:51:29,241] {dagbag.py:507} INFO - Filling up the DagBag from /home/kai/Documents/PROJETOS/twitter_extractor_airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-28 13:51:29,253] {logging_mixin.py:115} INFO - [2024-08-28 13:51:29,253] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/kai/Documents/PROJETOS/twitter_extractor_airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-08-28 13:51:29,253] {logging_mixin.py:115} INFO - [2024-08-28 13:51:29,253] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-08-28 13:51:29,253] {processor.py:653} WARNING - No viable dags retrieved from /home/kai/Documents/PROJETOS/twitter_extractor_airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-28 13:51:29,261] {processor.py:161} INFO - Processing /home/kai/Documents/PROJETOS/twitter_extractor_airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.024 seconds
[2024-08-28 13:52:00,168] {processor.py:153} INFO - Started process (PID=31803) to work on /home/kai/Documents/PROJETOS/twitter_extractor_airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-28 13:52:00,169] {processor.py:641} INFO - Processing file /home/kai/Documents/PROJETOS/twitter_extractor_airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-08-28 13:52:00,170] {logging_mixin.py:115} INFO - [2024-08-28 13:52:00,170] {dagbag.py:507} INFO - Filling up the DagBag from /home/kai/Documents/PROJETOS/twitter_extractor_airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-28 13:52:00,182] {logging_mixin.py:115} INFO - [2024-08-28 13:52:00,181] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/kai/Documents/PROJETOS/twitter_extractor_airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-08-28 13:52:00,182] {logging_mixin.py:115} INFO - [2024-08-28 13:52:00,182] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-08-28 13:52:00,182] {processor.py:653} WARNING - No viable dags retrieved from /home/kai/Documents/PROJETOS/twitter_extractor_airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-28 13:52:00,192] {processor.py:161} INFO - Processing /home/kai/Documents/PROJETOS/twitter_extractor_airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.028 seconds
[2024-08-28 13:52:32,260] {processor.py:153} INFO - Started process (PID=32279) to work on /home/kai/Documents/PROJETOS/twitter_extractor_airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-28 13:52:32,261] {processor.py:641} INFO - Processing file /home/kai/Documents/PROJETOS/twitter_extractor_airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-08-28 13:52:32,262] {logging_mixin.py:115} INFO - [2024-08-28 13:52:32,261] {dagbag.py:507} INFO - Filling up the DagBag from /home/kai/Documents/PROJETOS/twitter_extractor_airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-28 13:52:32,274] {logging_mixin.py:115} INFO - [2024-08-28 13:52:32,273] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/kai/Documents/PROJETOS/twitter_extractor_airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-08-28 13:52:32,274] {logging_mixin.py:115} INFO - [2024-08-28 13:52:32,274] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-08-28 13:52:32,274] {processor.py:653} WARNING - No viable dags retrieved from /home/kai/Documents/PROJETOS/twitter_extractor_airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-28 13:52:32,283] {processor.py:161} INFO - Processing /home/kai/Documents/PROJETOS/twitter_extractor_airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.025 seconds
[2024-08-28 13:53:07,425] {processor.py:153} INFO - Started process (PID=32823) to work on /home/kai/Documents/PROJETOS/twitter_extractor_airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-28 13:53:07,426] {processor.py:641} INFO - Processing file /home/kai/Documents/PROJETOS/twitter_extractor_airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-08-28 13:53:07,427] {logging_mixin.py:115} INFO - [2024-08-28 13:53:07,427] {dagbag.py:507} INFO - Filling up the DagBag from /home/kai/Documents/PROJETOS/twitter_extractor_airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-28 13:53:07,439] {logging_mixin.py:115} INFO - [2024-08-28 13:53:07,439] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/kai/Documents/PROJETOS/twitter_extractor_airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-08-28 13:53:07,439] {logging_mixin.py:115} INFO - [2024-08-28 13:53:07,439] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-08-28 13:53:07,439] {processor.py:653} WARNING - No viable dags retrieved from /home/kai/Documents/PROJETOS/twitter_extractor_airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-28 13:53:07,450] {processor.py:161} INFO - Processing /home/kai/Documents/PROJETOS/twitter_extractor_airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.028 seconds
[2024-08-28 13:53:42,499] {processor.py:153} INFO - Started process (PID=33027) to work on /home/kai/Documents/PROJETOS/twitter_extractor_airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-28 13:53:42,499] {processor.py:641} INFO - Processing file /home/kai/Documents/PROJETOS/twitter_extractor_airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-08-28 13:53:42,500] {logging_mixin.py:115} INFO - [2024-08-28 13:53:42,500] {dagbag.py:507} INFO - Filling up the DagBag from /home/kai/Documents/PROJETOS/twitter_extractor_airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-28 13:53:42,515] {logging_mixin.py:115} INFO - [2024-08-28 13:53:42,514] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/kai/Documents/PROJETOS/twitter_extractor_airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-08-28 13:53:42,515] {logging_mixin.py:115} INFO - [2024-08-28 13:53:42,515] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-08-28 13:53:42,515] {processor.py:653} WARNING - No viable dags retrieved from /home/kai/Documents/PROJETOS/twitter_extractor_airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-28 13:53:42,528] {processor.py:161} INFO - Processing /home/kai/Documents/PROJETOS/twitter_extractor_airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.032 seconds
[2024-08-28 13:54:14,349] {processor.py:153} INFO - Started process (PID=33204) to work on /home/kai/Documents/PROJETOS/twitter_extractor_airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-28 13:54:14,350] {processor.py:641} INFO - Processing file /home/kai/Documents/PROJETOS/twitter_extractor_airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-08-28 13:54:14,350] {logging_mixin.py:115} INFO - [2024-08-28 13:54:14,350] {dagbag.py:507} INFO - Filling up the DagBag from /home/kai/Documents/PROJETOS/twitter_extractor_airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-28 13:54:14,368] {logging_mixin.py:115} INFO - [2024-08-28 13:54:14,368] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/kai/Documents/PROJETOS/twitter_extractor_airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-08-28 13:54:14,368] {logging_mixin.py:115} INFO - [2024-08-28 13:54:14,368] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-08-28 13:54:14,368] {processor.py:653} WARNING - No viable dags retrieved from /home/kai/Documents/PROJETOS/twitter_extractor_airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-28 13:54:14,379] {processor.py:161} INFO - Processing /home/kai/Documents/PROJETOS/twitter_extractor_airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.033 seconds
[2024-08-28 13:54:48,477] {processor.py:153} INFO - Started process (PID=33623) to work on /home/kai/Documents/PROJETOS/twitter_extractor_airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-28 13:54:48,477] {processor.py:641} INFO - Processing file /home/kai/Documents/PROJETOS/twitter_extractor_airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-08-28 13:54:48,478] {logging_mixin.py:115} INFO - [2024-08-28 13:54:48,478] {dagbag.py:507} INFO - Filling up the DagBag from /home/kai/Documents/PROJETOS/twitter_extractor_airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-28 13:54:48,494] {logging_mixin.py:115} INFO - [2024-08-28 13:54:48,494] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/kai/Documents/PROJETOS/twitter_extractor_airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-08-28 13:54:48,494] {logging_mixin.py:115} INFO - [2024-08-28 13:54:48,494] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-08-28 13:54:48,495] {processor.py:653} WARNING - No viable dags retrieved from /home/kai/Documents/PROJETOS/twitter_extractor_airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-28 13:54:48,506] {processor.py:161} INFO - Processing /home/kai/Documents/PROJETOS/twitter_extractor_airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.031 seconds
[2024-08-28 13:55:21,201] {processor.py:153} INFO - Started process (PID=33880) to work on /home/kai/Documents/PROJETOS/twitter_extractor_airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-28 13:55:21,202] {processor.py:641} INFO - Processing file /home/kai/Documents/PROJETOS/twitter_extractor_airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-08-28 13:55:21,202] {logging_mixin.py:115} INFO - [2024-08-28 13:55:21,202] {dagbag.py:507} INFO - Filling up the DagBag from /home/kai/Documents/PROJETOS/twitter_extractor_airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-28 13:55:21,217] {logging_mixin.py:115} INFO - [2024-08-28 13:55:21,217] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/kai/Documents/PROJETOS/twitter_extractor_airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-08-28 13:55:21,217] {logging_mixin.py:115} INFO - [2024-08-28 13:55:21,217] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-08-28 13:55:21,218] {processor.py:653} WARNING - No viable dags retrieved from /home/kai/Documents/PROJETOS/twitter_extractor_airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-28 13:55:21,229] {processor.py:161} INFO - Processing /home/kai/Documents/PROJETOS/twitter_extractor_airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.031 seconds
[2024-08-28 13:55:54,369] {processor.py:153} INFO - Started process (PID=34079) to work on /home/kai/Documents/PROJETOS/twitter_extractor_airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-28 13:55:54,370] {processor.py:641} INFO - Processing file /home/kai/Documents/PROJETOS/twitter_extractor_airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-08-28 13:55:54,371] {logging_mixin.py:115} INFO - [2024-08-28 13:55:54,371] {dagbag.py:507} INFO - Filling up the DagBag from /home/kai/Documents/PROJETOS/twitter_extractor_airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-28 13:55:54,384] {logging_mixin.py:115} INFO - [2024-08-28 13:55:54,384] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/kai/Documents/PROJETOS/twitter_extractor_airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-08-28 13:55:54,384] {logging_mixin.py:115} INFO - [2024-08-28 13:55:54,384] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-08-28 13:55:54,385] {processor.py:653} WARNING - No viable dags retrieved from /home/kai/Documents/PROJETOS/twitter_extractor_airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-28 13:55:54,393] {processor.py:161} INFO - Processing /home/kai/Documents/PROJETOS/twitter_extractor_airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.028 seconds
[2024-08-28 13:56:25,032] {processor.py:153} INFO - Started process (PID=34263) to work on /home/kai/Documents/PROJETOS/twitter_extractor_airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-28 13:56:25,034] {processor.py:641} INFO - Processing file /home/kai/Documents/PROJETOS/twitter_extractor_airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-08-28 13:56:25,034] {logging_mixin.py:115} INFO - [2024-08-28 13:56:25,034] {dagbag.py:507} INFO - Filling up the DagBag from /home/kai/Documents/PROJETOS/twitter_extractor_airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-28 13:56:25,051] {logging_mixin.py:115} INFO - [2024-08-28 13:56:25,051] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/kai/Documents/PROJETOS/twitter_extractor_airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-08-28 13:56:25,051] {logging_mixin.py:115} INFO - [2024-08-28 13:56:25,051] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-08-28 13:56:25,051] {processor.py:653} WARNING - No viable dags retrieved from /home/kai/Documents/PROJETOS/twitter_extractor_airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-28 13:56:25,062] {processor.py:161} INFO - Processing /home/kai/Documents/PROJETOS/twitter_extractor_airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.035 seconds
[2024-08-28 13:56:55,340] {processor.py:153} INFO - Started process (PID=34615) to work on /home/kai/Documents/PROJETOS/twitter_extractor_airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-28 13:56:55,341] {processor.py:641} INFO - Processing file /home/kai/Documents/PROJETOS/twitter_extractor_airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-08-28 13:56:55,342] {logging_mixin.py:115} INFO - [2024-08-28 13:56:55,341] {dagbag.py:507} INFO - Filling up the DagBag from /home/kai/Documents/PROJETOS/twitter_extractor_airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-28 13:56:55,353] {logging_mixin.py:115} INFO - [2024-08-28 13:56:55,353] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/kai/Documents/PROJETOS/twitter_extractor_airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-08-28 13:56:55,353] {logging_mixin.py:115} INFO - [2024-08-28 13:56:55,353] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-08-28 13:56:55,353] {processor.py:653} WARNING - No viable dags retrieved from /home/kai/Documents/PROJETOS/twitter_extractor_airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-28 13:56:55,362] {processor.py:161} INFO - Processing /home/kai/Documents/PROJETOS/twitter_extractor_airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.024 seconds
[2024-08-28 13:57:26,669] {processor.py:153} INFO - Started process (PID=35005) to work on /home/kai/Documents/PROJETOS/twitter_extractor_airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-28 13:57:26,669] {processor.py:641} INFO - Processing file /home/kai/Documents/PROJETOS/twitter_extractor_airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-08-28 13:57:26,670] {logging_mixin.py:115} INFO - [2024-08-28 13:57:26,670] {dagbag.py:507} INFO - Filling up the DagBag from /home/kai/Documents/PROJETOS/twitter_extractor_airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-28 13:57:26,683] {logging_mixin.py:115} INFO - [2024-08-28 13:57:26,682] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/kai/Documents/PROJETOS/twitter_extractor_airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-08-28 13:57:26,683] {logging_mixin.py:115} INFO - [2024-08-28 13:57:26,683] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-08-28 13:57:26,683] {processor.py:653} WARNING - No viable dags retrieved from /home/kai/Documents/PROJETOS/twitter_extractor_airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-28 13:57:26,691] {processor.py:161} INFO - Processing /home/kai/Documents/PROJETOS/twitter_extractor_airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.025 seconds
[2024-08-28 13:57:58,847] {processor.py:153} INFO - Started process (PID=35228) to work on /home/kai/Documents/PROJETOS/twitter_extractor_airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-28 13:57:58,848] {processor.py:641} INFO - Processing file /home/kai/Documents/PROJETOS/twitter_extractor_airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-08-28 13:57:58,848] {logging_mixin.py:115} INFO - [2024-08-28 13:57:58,848] {dagbag.py:507} INFO - Filling up the DagBag from /home/kai/Documents/PROJETOS/twitter_extractor_airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-28 13:57:58,861] {logging_mixin.py:115} INFO - [2024-08-28 13:57:58,861] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/kai/Documents/PROJETOS/twitter_extractor_airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-08-28 13:57:58,861] {logging_mixin.py:115} INFO - [2024-08-28 13:57:58,861] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-08-28 13:57:58,862] {processor.py:653} WARNING - No viable dags retrieved from /home/kai/Documents/PROJETOS/twitter_extractor_airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-28 13:57:58,872] {processor.py:161} INFO - Processing /home/kai/Documents/PROJETOS/twitter_extractor_airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.028 seconds
[2024-08-28 13:58:32,722] {processor.py:153} INFO - Started process (PID=35463) to work on /home/kai/Documents/PROJETOS/twitter_extractor_airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-28 13:58:32,723] {processor.py:641} INFO - Processing file /home/kai/Documents/PROJETOS/twitter_extractor_airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-08-28 13:58:32,723] {logging_mixin.py:115} INFO - [2024-08-28 13:58:32,723] {dagbag.py:507} INFO - Filling up the DagBag from /home/kai/Documents/PROJETOS/twitter_extractor_airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-28 13:58:32,735] {logging_mixin.py:115} INFO - [2024-08-28 13:58:32,734] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/kai/Documents/PROJETOS/twitter_extractor_airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-08-28 13:58:32,735] {logging_mixin.py:115} INFO - [2024-08-28 13:58:32,735] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-08-28 13:58:32,735] {processor.py:653} WARNING - No viable dags retrieved from /home/kai/Documents/PROJETOS/twitter_extractor_airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-28 13:58:32,743] {processor.py:161} INFO - Processing /home/kai/Documents/PROJETOS/twitter_extractor_airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.023 seconds
[2024-08-28 13:59:06,154] {processor.py:153} INFO - Started process (PID=35869) to work on /home/kai/Documents/PROJETOS/twitter_extractor_airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-28 13:59:06,155] {processor.py:641} INFO - Processing file /home/kai/Documents/PROJETOS/twitter_extractor_airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-08-28 13:59:06,155] {logging_mixin.py:115} INFO - [2024-08-28 13:59:06,155] {dagbag.py:507} INFO - Filling up the DagBag from /home/kai/Documents/PROJETOS/twitter_extractor_airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-28 13:59:06,168] {logging_mixin.py:115} INFO - [2024-08-28 13:59:06,168] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/kai/Documents/PROJETOS/twitter_extractor_airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-08-28 13:59:06,169] {logging_mixin.py:115} INFO - [2024-08-28 13:59:06,168] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-08-28 13:59:06,169] {processor.py:653} WARNING - No viable dags retrieved from /home/kai/Documents/PROJETOS/twitter_extractor_airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-28 13:59:06,179] {processor.py:161} INFO - Processing /home/kai/Documents/PROJETOS/twitter_extractor_airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.028 seconds
[2024-08-28 13:59:41,456] {processor.py:153} INFO - Started process (PID=36188) to work on /home/kai/Documents/PROJETOS/twitter_extractor_airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-28 13:59:41,457] {processor.py:641} INFO - Processing file /home/kai/Documents/PROJETOS/twitter_extractor_airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-08-28 13:59:41,457] {logging_mixin.py:115} INFO - [2024-08-28 13:59:41,457] {dagbag.py:507} INFO - Filling up the DagBag from /home/kai/Documents/PROJETOS/twitter_extractor_airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-28 13:59:41,469] {logging_mixin.py:115} INFO - [2024-08-28 13:59:41,469] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/kai/Documents/PROJETOS/twitter_extractor_airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-08-28 13:59:41,469] {logging_mixin.py:115} INFO - [2024-08-28 13:59:41,469] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-08-28 13:59:41,469] {processor.py:653} WARNING - No viable dags retrieved from /home/kai/Documents/PROJETOS/twitter_extractor_airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-28 13:59:41,478] {processor.py:161} INFO - Processing /home/kai/Documents/PROJETOS/twitter_extractor_airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.024 seconds
[2024-08-28 14:00:13,679] {processor.py:153} INFO - Started process (PID=36481) to work on /home/kai/Documents/PROJETOS/twitter_extractor_airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-28 14:00:13,680] {processor.py:641} INFO - Processing file /home/kai/Documents/PROJETOS/twitter_extractor_airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-08-28 14:00:13,680] {logging_mixin.py:115} INFO - [2024-08-28 14:00:13,680] {dagbag.py:507} INFO - Filling up the DagBag from /home/kai/Documents/PROJETOS/twitter_extractor_airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-28 14:00:13,693] {logging_mixin.py:115} INFO - [2024-08-28 14:00:13,693] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/kai/Documents/PROJETOS/twitter_extractor_airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-08-28 14:00:13,693] {logging_mixin.py:115} INFO - [2024-08-28 14:00:13,693] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-08-28 14:00:13,693] {processor.py:653} WARNING - No viable dags retrieved from /home/kai/Documents/PROJETOS/twitter_extractor_airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-28 14:00:13,703] {processor.py:161} INFO - Processing /home/kai/Documents/PROJETOS/twitter_extractor_airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.026 seconds
[2024-08-28 14:00:49,655] {processor.py:153} INFO - Started process (PID=36746) to work on /home/kai/Documents/PROJETOS/twitter_extractor_airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-28 14:00:49,656] {processor.py:641} INFO - Processing file /home/kai/Documents/PROJETOS/twitter_extractor_airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-08-28 14:00:49,656] {logging_mixin.py:115} INFO - [2024-08-28 14:00:49,656] {dagbag.py:507} INFO - Filling up the DagBag from /home/kai/Documents/PROJETOS/twitter_extractor_airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-28 14:00:49,667] {logging_mixin.py:115} INFO - [2024-08-28 14:00:49,667] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/kai/Documents/PROJETOS/twitter_extractor_airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-08-28 14:00:49,668] {logging_mixin.py:115} INFO - [2024-08-28 14:00:49,668] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-08-28 14:00:49,668] {processor.py:653} WARNING - No viable dags retrieved from /home/kai/Documents/PROJETOS/twitter_extractor_airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-28 14:00:49,676] {processor.py:161} INFO - Processing /home/kai/Documents/PROJETOS/twitter_extractor_airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.023 seconds
[2024-08-28 14:01:20,548] {processor.py:153} INFO - Started process (PID=37141) to work on /home/kai/Documents/PROJETOS/twitter_extractor_airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-28 14:01:20,549] {processor.py:641} INFO - Processing file /home/kai/Documents/PROJETOS/twitter_extractor_airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-08-28 14:01:20,549] {logging_mixin.py:115} INFO - [2024-08-28 14:01:20,549] {dagbag.py:507} INFO - Filling up the DagBag from /home/kai/Documents/PROJETOS/twitter_extractor_airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-28 14:01:20,561] {logging_mixin.py:115} INFO - [2024-08-28 14:01:20,561] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/kai/Documents/PROJETOS/twitter_extractor_airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-08-28 14:01:20,562] {logging_mixin.py:115} INFO - [2024-08-28 14:01:20,562] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-08-28 14:01:20,562] {processor.py:653} WARNING - No viable dags retrieved from /home/kai/Documents/PROJETOS/twitter_extractor_airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-28 14:01:20,570] {processor.py:161} INFO - Processing /home/kai/Documents/PROJETOS/twitter_extractor_airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.025 seconds
[2024-08-28 14:01:53,107] {processor.py:153} INFO - Started process (PID=37548) to work on /home/kai/Documents/PROJETOS/twitter_extractor_airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-28 14:01:53,108] {processor.py:641} INFO - Processing file /home/kai/Documents/PROJETOS/twitter_extractor_airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-08-28 14:01:53,109] {logging_mixin.py:115} INFO - [2024-08-28 14:01:53,109] {dagbag.py:507} INFO - Filling up the DagBag from /home/kai/Documents/PROJETOS/twitter_extractor_airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-28 14:01:53,127] {logging_mixin.py:115} INFO - [2024-08-28 14:01:53,126] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/kai/Documents/PROJETOS/twitter_extractor_airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-08-28 14:01:53,127] {logging_mixin.py:115} INFO - [2024-08-28 14:01:53,127] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-08-28 14:01:53,127] {processor.py:653} WARNING - No viable dags retrieved from /home/kai/Documents/PROJETOS/twitter_extractor_airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-28 14:01:53,138] {processor.py:161} INFO - Processing /home/kai/Documents/PROJETOS/twitter_extractor_airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.034 seconds
[2024-08-28 14:02:25,791] {processor.py:153} INFO - Started process (PID=37838) to work on /home/kai/Documents/PROJETOS/twitter_extractor_airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-28 14:02:25,792] {processor.py:641} INFO - Processing file /home/kai/Documents/PROJETOS/twitter_extractor_airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-08-28 14:02:25,793] {logging_mixin.py:115} INFO - [2024-08-28 14:02:25,792] {dagbag.py:507} INFO - Filling up the DagBag from /home/kai/Documents/PROJETOS/twitter_extractor_airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-28 14:02:25,808] {logging_mixin.py:115} INFO - [2024-08-28 14:02:25,807] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/kai/Documents/PROJETOS/twitter_extractor_airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-08-28 14:02:25,808] {logging_mixin.py:115} INFO - [2024-08-28 14:02:25,808] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-08-28 14:02:25,808] {processor.py:653} WARNING - No viable dags retrieved from /home/kai/Documents/PROJETOS/twitter_extractor_airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-28 14:02:25,819] {processor.py:161} INFO - Processing /home/kai/Documents/PROJETOS/twitter_extractor_airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.030 seconds
[2024-08-28 14:02:58,442] {processor.py:153} INFO - Started process (PID=38051) to work on /home/kai/Documents/PROJETOS/twitter_extractor_airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-28 14:02:58,442] {processor.py:641} INFO - Processing file /home/kai/Documents/PROJETOS/twitter_extractor_airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-08-28 14:02:58,443] {logging_mixin.py:115} INFO - [2024-08-28 14:02:58,443] {dagbag.py:507} INFO - Filling up the DagBag from /home/kai/Documents/PROJETOS/twitter_extractor_airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-28 14:02:58,455] {logging_mixin.py:115} INFO - [2024-08-28 14:02:58,455] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/kai/Documents/PROJETOS/twitter_extractor_airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-08-28 14:02:58,456] {logging_mixin.py:115} INFO - [2024-08-28 14:02:58,455] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-08-28 14:02:58,456] {processor.py:653} WARNING - No viable dags retrieved from /home/kai/Documents/PROJETOS/twitter_extractor_airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-28 14:02:58,466] {processor.py:161} INFO - Processing /home/kai/Documents/PROJETOS/twitter_extractor_airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.026 seconds
[2024-08-28 14:03:30,058] {processor.py:153} INFO - Started process (PID=38291) to work on /home/kai/Documents/PROJETOS/twitter_extractor_airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-28 14:03:30,058] {processor.py:641} INFO - Processing file /home/kai/Documents/PROJETOS/twitter_extractor_airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-08-28 14:03:30,059] {logging_mixin.py:115} INFO - [2024-08-28 14:03:30,059] {dagbag.py:507} INFO - Filling up the DagBag from /home/kai/Documents/PROJETOS/twitter_extractor_airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-28 14:03:30,071] {logging_mixin.py:115} INFO - [2024-08-28 14:03:30,070] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/kai/Documents/PROJETOS/twitter_extractor_airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-08-28 14:03:30,071] {logging_mixin.py:115} INFO - [2024-08-28 14:03:30,071] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-08-28 14:03:30,071] {processor.py:653} WARNING - No viable dags retrieved from /home/kai/Documents/PROJETOS/twitter_extractor_airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-28 14:03:30,080] {processor.py:161} INFO - Processing /home/kai/Documents/PROJETOS/twitter_extractor_airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.025 seconds
[2024-08-28 14:04:04,825] {processor.py:153} INFO - Started process (PID=38505) to work on /home/kai/Documents/PROJETOS/twitter_extractor_airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-28 14:04:04,827] {processor.py:641} INFO - Processing file /home/kai/Documents/PROJETOS/twitter_extractor_airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-08-28 14:04:04,827] {logging_mixin.py:115} INFO - [2024-08-28 14:04:04,827] {dagbag.py:507} INFO - Filling up the DagBag from /home/kai/Documents/PROJETOS/twitter_extractor_airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-28 14:04:04,840] {logging_mixin.py:115} INFO - [2024-08-28 14:04:04,840] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/kai/Documents/PROJETOS/twitter_extractor_airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-08-28 14:04:04,840] {logging_mixin.py:115} INFO - [2024-08-28 14:04:04,840] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-08-28 14:04:04,841] {processor.py:653} WARNING - No viable dags retrieved from /home/kai/Documents/PROJETOS/twitter_extractor_airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-28 14:04:04,850] {processor.py:161} INFO - Processing /home/kai/Documents/PROJETOS/twitter_extractor_airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.027 seconds
[2024-08-28 14:04:35,914] {processor.py:153} INFO - Started process (PID=38722) to work on /home/kai/Documents/PROJETOS/twitter_extractor_airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-28 14:04:35,915] {processor.py:641} INFO - Processing file /home/kai/Documents/PROJETOS/twitter_extractor_airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-08-28 14:04:35,915] {logging_mixin.py:115} INFO - [2024-08-28 14:04:35,915] {dagbag.py:507} INFO - Filling up the DagBag from /home/kai/Documents/PROJETOS/twitter_extractor_airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-28 14:04:35,927] {logging_mixin.py:115} INFO - [2024-08-28 14:04:35,927] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/kai/Documents/PROJETOS/twitter_extractor_airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-08-28 14:04:35,927] {logging_mixin.py:115} INFO - [2024-08-28 14:04:35,927] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-08-28 14:04:35,928] {processor.py:653} WARNING - No viable dags retrieved from /home/kai/Documents/PROJETOS/twitter_extractor_airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-28 14:04:35,936] {processor.py:161} INFO - Processing /home/kai/Documents/PROJETOS/twitter_extractor_airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.024 seconds
[2024-08-28 14:05:10,176] {processor.py:153} INFO - Started process (PID=38921) to work on /home/kai/Documents/PROJETOS/twitter_extractor_airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-28 14:05:10,177] {processor.py:641} INFO - Processing file /home/kai/Documents/PROJETOS/twitter_extractor_airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-08-28 14:05:10,177] {logging_mixin.py:115} INFO - [2024-08-28 14:05:10,177] {dagbag.py:507} INFO - Filling up the DagBag from /home/kai/Documents/PROJETOS/twitter_extractor_airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-28 14:05:10,190] {logging_mixin.py:115} INFO - [2024-08-28 14:05:10,189] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/kai/Documents/PROJETOS/twitter_extractor_airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-08-28 14:05:10,190] {logging_mixin.py:115} INFO - [2024-08-28 14:05:10,190] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-08-28 14:05:10,190] {processor.py:653} WARNING - No viable dags retrieved from /home/kai/Documents/PROJETOS/twitter_extractor_airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-28 14:05:10,200] {processor.py:161} INFO - Processing /home/kai/Documents/PROJETOS/twitter_extractor_airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.027 seconds
[2024-08-28 14:05:42,795] {processor.py:153} INFO - Started process (PID=39173) to work on /home/kai/Documents/PROJETOS/twitter_extractor_airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-28 14:05:42,795] {processor.py:641} INFO - Processing file /home/kai/Documents/PROJETOS/twitter_extractor_airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-08-28 14:05:42,796] {logging_mixin.py:115} INFO - [2024-08-28 14:05:42,796] {dagbag.py:507} INFO - Filling up the DagBag from /home/kai/Documents/PROJETOS/twitter_extractor_airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-28 14:05:42,807] {logging_mixin.py:115} INFO - [2024-08-28 14:05:42,807] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/kai/Documents/PROJETOS/twitter_extractor_airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-08-28 14:05:42,807] {logging_mixin.py:115} INFO - [2024-08-28 14:05:42,807] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-08-28 14:05:42,807] {processor.py:653} WARNING - No viable dags retrieved from /home/kai/Documents/PROJETOS/twitter_extractor_airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-28 14:05:42,815] {processor.py:161} INFO - Processing /home/kai/Documents/PROJETOS/twitter_extractor_airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.023 seconds
[2024-08-28 14:33:39,638] {processor.py:153} INFO - Started process (PID=45205) to work on /home/kai/Documents/PROJETOS/twitter_extractor_airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-28 14:33:39,639] {processor.py:641} INFO - Processing file /home/kai/Documents/PROJETOS/twitter_extractor_airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-08-28 14:33:39,640] {logging_mixin.py:115} INFO - [2024-08-28 14:33:39,640] {dagbag.py:507} INFO - Filling up the DagBag from /home/kai/Documents/PROJETOS/twitter_extractor_airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-28 14:33:39,656] {logging_mixin.py:115} INFO - [2024-08-28 14:33:39,655] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/kai/Documents/PROJETOS/twitter_extractor_airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-08-28 14:33:39,656] {logging_mixin.py:115} INFO - [2024-08-28 14:33:39,656] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-08-28 14:33:39,656] {processor.py:653} WARNING - No viable dags retrieved from /home/kai/Documents/PROJETOS/twitter_extractor_airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-28 14:33:39,668] {processor.py:161} INFO - Processing /home/kai/Documents/PROJETOS/twitter_extractor_airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.034 seconds
[2024-08-28 14:34:13,647] {processor.py:153} INFO - Started process (PID=45564) to work on /home/kai/Documents/PROJETOS/twitter_extractor_airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-28 14:34:13,647] {processor.py:641} INFO - Processing file /home/kai/Documents/PROJETOS/twitter_extractor_airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-08-28 14:34:13,648] {logging_mixin.py:115} INFO - [2024-08-28 14:34:13,648] {dagbag.py:507} INFO - Filling up the DagBag from /home/kai/Documents/PROJETOS/twitter_extractor_airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-28 14:34:13,659] {logging_mixin.py:115} INFO - [2024-08-28 14:34:13,658] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/kai/Documents/PROJETOS/twitter_extractor_airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-08-28 14:34:13,659] {logging_mixin.py:115} INFO - [2024-08-28 14:34:13,659] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-08-28 14:34:13,659] {processor.py:653} WARNING - No viable dags retrieved from /home/kai/Documents/PROJETOS/twitter_extractor_airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-28 14:34:13,668] {processor.py:161} INFO - Processing /home/kai/Documents/PROJETOS/twitter_extractor_airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.023 seconds
[2024-08-28 14:34:46,275] {processor.py:153} INFO - Started process (PID=45813) to work on /home/kai/Documents/PROJETOS/twitter_extractor_airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-28 14:34:46,276] {processor.py:641} INFO - Processing file /home/kai/Documents/PROJETOS/twitter_extractor_airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-08-28 14:34:46,276] {logging_mixin.py:115} INFO - [2024-08-28 14:34:46,276] {dagbag.py:507} INFO - Filling up the DagBag from /home/kai/Documents/PROJETOS/twitter_extractor_airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-28 14:34:46,287] {logging_mixin.py:115} INFO - [2024-08-28 14:34:46,287] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/kai/Documents/PROJETOS/twitter_extractor_airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-08-28 14:34:46,287] {logging_mixin.py:115} INFO - [2024-08-28 14:34:46,287] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-08-28 14:34:46,287] {processor.py:653} WARNING - No viable dags retrieved from /home/kai/Documents/PROJETOS/twitter_extractor_airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-28 14:34:46,295] {processor.py:161} INFO - Processing /home/kai/Documents/PROJETOS/twitter_extractor_airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.023 seconds
[2024-08-28 14:35:20,029] {processor.py:153} INFO - Started process (PID=46010) to work on /home/kai/Documents/PROJETOS/twitter_extractor_airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-28 14:35:20,030] {processor.py:641} INFO - Processing file /home/kai/Documents/PROJETOS/twitter_extractor_airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-08-28 14:35:20,030] {logging_mixin.py:115} INFO - [2024-08-28 14:35:20,030] {dagbag.py:507} INFO - Filling up the DagBag from /home/kai/Documents/PROJETOS/twitter_extractor_airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-28 14:35:20,046] {logging_mixin.py:115} INFO - [2024-08-28 14:35:20,045] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/kai/Documents/PROJETOS/twitter_extractor_airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-08-28 14:35:20,046] {logging_mixin.py:115} INFO - [2024-08-28 14:35:20,046] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-08-28 14:35:20,046] {processor.py:653} WARNING - No viable dags retrieved from /home/kai/Documents/PROJETOS/twitter_extractor_airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-28 14:35:20,056] {processor.py:161} INFO - Processing /home/kai/Documents/PROJETOS/twitter_extractor_airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.030 seconds
[2024-08-28 14:35:53,324] {processor.py:153} INFO - Started process (PID=46208) to work on /home/kai/Documents/PROJETOS/twitter_extractor_airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-28 14:35:53,325] {processor.py:641} INFO - Processing file /home/kai/Documents/PROJETOS/twitter_extractor_airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-08-28 14:35:53,326] {logging_mixin.py:115} INFO - [2024-08-28 14:35:53,325] {dagbag.py:507} INFO - Filling up the DagBag from /home/kai/Documents/PROJETOS/twitter_extractor_airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-28 14:35:53,336] {logging_mixin.py:115} INFO - [2024-08-28 14:35:53,336] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/kai/Documents/PROJETOS/twitter_extractor_airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-08-28 14:35:53,337] {logging_mixin.py:115} INFO - [2024-08-28 14:35:53,337] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-08-28 14:35:53,337] {processor.py:653} WARNING - No viable dags retrieved from /home/kai/Documents/PROJETOS/twitter_extractor_airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-28 14:35:53,346] {processor.py:161} INFO - Processing /home/kai/Documents/PROJETOS/twitter_extractor_airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.024 seconds
[2024-08-28 14:36:28,244] {processor.py:153} INFO - Started process (PID=46412) to work on /home/kai/Documents/PROJETOS/twitter_extractor_airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-28 14:36:28,245] {processor.py:641} INFO - Processing file /home/kai/Documents/PROJETOS/twitter_extractor_airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-08-28 14:36:28,245] {logging_mixin.py:115} INFO - [2024-08-28 14:36:28,245] {dagbag.py:507} INFO - Filling up the DagBag from /home/kai/Documents/PROJETOS/twitter_extractor_airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-28 14:36:28,257] {logging_mixin.py:115} INFO - [2024-08-28 14:36:28,256] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/kai/Documents/PROJETOS/twitter_extractor_airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-08-28 14:36:28,257] {logging_mixin.py:115} INFO - [2024-08-28 14:36:28,257] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-08-28 14:36:28,257] {processor.py:653} WARNING - No viable dags retrieved from /home/kai/Documents/PROJETOS/twitter_extractor_airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-28 14:36:28,265] {processor.py:161} INFO - Processing /home/kai/Documents/PROJETOS/twitter_extractor_airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.023 seconds
[2024-08-28 14:37:00,298] {processor.py:153} INFO - Started process (PID=46622) to work on /home/kai/Documents/PROJETOS/twitter_extractor_airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-28 14:37:00,299] {processor.py:641} INFO - Processing file /home/kai/Documents/PROJETOS/twitter_extractor_airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-08-28 14:37:00,300] {logging_mixin.py:115} INFO - [2024-08-28 14:37:00,300] {dagbag.py:507} INFO - Filling up the DagBag from /home/kai/Documents/PROJETOS/twitter_extractor_airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-28 14:37:00,314] {logging_mixin.py:115} INFO - [2024-08-28 14:37:00,314] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/kai/Documents/PROJETOS/twitter_extractor_airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-08-28 14:37:00,315] {logging_mixin.py:115} INFO - [2024-08-28 14:37:00,314] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-08-28 14:37:00,315] {processor.py:653} WARNING - No viable dags retrieved from /home/kai/Documents/PROJETOS/twitter_extractor_airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-28 14:37:00,325] {processor.py:161} INFO - Processing /home/kai/Documents/PROJETOS/twitter_extractor_airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.029 seconds
[2024-08-28 14:37:33,052] {processor.py:153} INFO - Started process (PID=46869) to work on /home/kai/Documents/PROJETOS/twitter_extractor_airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-28 14:37:33,052] {processor.py:641} INFO - Processing file /home/kai/Documents/PROJETOS/twitter_extractor_airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-08-28 14:37:33,053] {logging_mixin.py:115} INFO - [2024-08-28 14:37:33,053] {dagbag.py:507} INFO - Filling up the DagBag from /home/kai/Documents/PROJETOS/twitter_extractor_airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-28 14:37:33,066] {logging_mixin.py:115} INFO - [2024-08-28 14:37:33,066] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/kai/Documents/PROJETOS/twitter_extractor_airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-08-28 14:37:33,066] {logging_mixin.py:115} INFO - [2024-08-28 14:37:33,066] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-08-28 14:37:33,066] {processor.py:653} WARNING - No viable dags retrieved from /home/kai/Documents/PROJETOS/twitter_extractor_airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-28 14:37:33,077] {processor.py:161} INFO - Processing /home/kai/Documents/PROJETOS/twitter_extractor_airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.029 seconds
[2024-08-28 14:38:05,700] {processor.py:153} INFO - Started process (PID=47201) to work on /home/kai/Documents/PROJETOS/twitter_extractor_airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-28 14:38:05,700] {processor.py:641} INFO - Processing file /home/kai/Documents/PROJETOS/twitter_extractor_airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-08-28 14:38:05,701] {logging_mixin.py:115} INFO - [2024-08-28 14:38:05,701] {dagbag.py:507} INFO - Filling up the DagBag from /home/kai/Documents/PROJETOS/twitter_extractor_airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-28 14:38:05,712] {logging_mixin.py:115} INFO - [2024-08-28 14:38:05,712] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/kai/Documents/PROJETOS/twitter_extractor_airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-08-28 14:38:05,712] {logging_mixin.py:115} INFO - [2024-08-28 14:38:05,712] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-08-28 14:38:05,712] {processor.py:653} WARNING - No viable dags retrieved from /home/kai/Documents/PROJETOS/twitter_extractor_airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-28 14:38:05,721] {processor.py:161} INFO - Processing /home/kai/Documents/PROJETOS/twitter_extractor_airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.024 seconds
[2024-08-28 14:38:39,501] {processor.py:153} INFO - Started process (PID=47493) to work on /home/kai/Documents/PROJETOS/twitter_extractor_airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-28 14:38:39,502] {processor.py:641} INFO - Processing file /home/kai/Documents/PROJETOS/twitter_extractor_airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-08-28 14:38:39,503] {logging_mixin.py:115} INFO - [2024-08-28 14:38:39,502] {dagbag.py:507} INFO - Filling up the DagBag from /home/kai/Documents/PROJETOS/twitter_extractor_airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-28 14:38:39,514] {logging_mixin.py:115} INFO - [2024-08-28 14:38:39,514] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/kai/Documents/PROJETOS/twitter_extractor_airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-08-28 14:38:39,514] {logging_mixin.py:115} INFO - [2024-08-28 14:38:39,514] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-08-28 14:38:39,514] {processor.py:653} WARNING - No viable dags retrieved from /home/kai/Documents/PROJETOS/twitter_extractor_airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-28 14:38:39,524] {processor.py:161} INFO - Processing /home/kai/Documents/PROJETOS/twitter_extractor_airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.025 seconds
[2024-08-28 14:39:07,907] {processor.py:153} INFO - Started process (PID=47871) to work on /home/kai/Documents/PROJETOS/twitter_extractor_airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-28 14:39:07,908] {processor.py:641} INFO - Processing file /home/kai/Documents/PROJETOS/twitter_extractor_airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-08-28 14:39:07,909] {logging_mixin.py:115} INFO - [2024-08-28 14:39:07,909] {dagbag.py:507} INFO - Filling up the DagBag from /home/kai/Documents/PROJETOS/twitter_extractor_airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-28 14:39:07,923] {logging_mixin.py:115} INFO - [2024-08-28 14:39:07,923] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/kai/Documents/PROJETOS/twitter_extractor_airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-08-28 14:39:07,923] {logging_mixin.py:115} INFO - [2024-08-28 14:39:07,923] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-08-28 14:39:07,923] {processor.py:653} WARNING - No viable dags retrieved from /home/kai/Documents/PROJETOS/twitter_extractor_airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-28 14:39:07,937] {processor.py:161} INFO - Processing /home/kai/Documents/PROJETOS/twitter_extractor_airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.033 seconds
[2024-08-28 14:39:39,978] {processor.py:153} INFO - Started process (PID=48113) to work on /home/kai/Documents/PROJETOS/twitter_extractor_airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-28 14:39:39,979] {processor.py:641} INFO - Processing file /home/kai/Documents/PROJETOS/twitter_extractor_airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-08-28 14:39:39,979] {logging_mixin.py:115} INFO - [2024-08-28 14:39:39,979] {dagbag.py:507} INFO - Filling up the DagBag from /home/kai/Documents/PROJETOS/twitter_extractor_airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-28 14:39:39,990] {logging_mixin.py:115} INFO - [2024-08-28 14:39:39,990] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/kai/Documents/PROJETOS/twitter_extractor_airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-08-28 14:39:39,990] {logging_mixin.py:115} INFO - [2024-08-28 14:39:39,990] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-08-28 14:39:39,990] {processor.py:653} WARNING - No viable dags retrieved from /home/kai/Documents/PROJETOS/twitter_extractor_airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-28 14:39:40,001] {processor.py:161} INFO - Processing /home/kai/Documents/PROJETOS/twitter_extractor_airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.025 seconds
[2024-08-28 14:40:14,368] {processor.py:153} INFO - Started process (PID=48354) to work on /home/kai/Documents/PROJETOS/twitter_extractor_airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-28 14:40:14,369] {processor.py:641} INFO - Processing file /home/kai/Documents/PROJETOS/twitter_extractor_airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-08-28 14:40:14,369] {logging_mixin.py:115} INFO - [2024-08-28 14:40:14,369] {dagbag.py:507} INFO - Filling up the DagBag from /home/kai/Documents/PROJETOS/twitter_extractor_airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-28 14:40:14,381] {logging_mixin.py:115} INFO - [2024-08-28 14:40:14,381] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/kai/Documents/PROJETOS/twitter_extractor_airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-08-28 14:40:14,381] {logging_mixin.py:115} INFO - [2024-08-28 14:40:14,381] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-08-28 14:40:14,381] {processor.py:653} WARNING - No viable dags retrieved from /home/kai/Documents/PROJETOS/twitter_extractor_airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-28 14:40:14,389] {processor.py:161} INFO - Processing /home/kai/Documents/PROJETOS/twitter_extractor_airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.024 seconds
[2024-08-28 14:40:46,882] {processor.py:153} INFO - Started process (PID=48544) to work on /home/kai/Documents/PROJETOS/twitter_extractor_airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-28 14:40:46,883] {processor.py:641} INFO - Processing file /home/kai/Documents/PROJETOS/twitter_extractor_airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-08-28 14:40:46,884] {logging_mixin.py:115} INFO - [2024-08-28 14:40:46,883] {dagbag.py:507} INFO - Filling up the DagBag from /home/kai/Documents/PROJETOS/twitter_extractor_airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-28 14:40:46,895] {logging_mixin.py:115} INFO - [2024-08-28 14:40:46,895] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/kai/Documents/PROJETOS/twitter_extractor_airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-08-28 14:40:46,896] {logging_mixin.py:115} INFO - [2024-08-28 14:40:46,896] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-08-28 14:40:46,896] {processor.py:653} WARNING - No viable dags retrieved from /home/kai/Documents/PROJETOS/twitter_extractor_airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-28 14:40:46,905] {processor.py:161} INFO - Processing /home/kai/Documents/PROJETOS/twitter_extractor_airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.026 seconds
[2024-08-28 14:41:21,929] {processor.py:153} INFO - Started process (PID=48888) to work on /home/kai/Documents/PROJETOS/twitter_extractor_airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-28 14:41:21,930] {processor.py:641} INFO - Processing file /home/kai/Documents/PROJETOS/twitter_extractor_airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-08-28 14:41:21,931] {logging_mixin.py:115} INFO - [2024-08-28 14:41:21,931] {dagbag.py:507} INFO - Filling up the DagBag from /home/kai/Documents/PROJETOS/twitter_extractor_airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-28 14:41:21,950] {logging_mixin.py:115} INFO - [2024-08-28 14:41:21,950] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/kai/Documents/PROJETOS/twitter_extractor_airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-08-28 14:41:21,950] {logging_mixin.py:115} INFO - [2024-08-28 14:41:21,950] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-08-28 14:41:21,950] {processor.py:653} WARNING - No viable dags retrieved from /home/kai/Documents/PROJETOS/twitter_extractor_airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-28 14:41:21,964] {processor.py:161} INFO - Processing /home/kai/Documents/PROJETOS/twitter_extractor_airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.039 seconds
[2024-08-28 14:41:55,186] {processor.py:153} INFO - Started process (PID=49089) to work on /home/kai/Documents/PROJETOS/twitter_extractor_airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-28 14:41:55,186] {processor.py:641} INFO - Processing file /home/kai/Documents/PROJETOS/twitter_extractor_airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-08-28 14:41:55,187] {logging_mixin.py:115} INFO - [2024-08-28 14:41:55,187] {dagbag.py:507} INFO - Filling up the DagBag from /home/kai/Documents/PROJETOS/twitter_extractor_airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-28 14:41:55,198] {logging_mixin.py:115} INFO - [2024-08-28 14:41:55,197] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/kai/Documents/PROJETOS/twitter_extractor_airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-08-28 14:41:55,198] {logging_mixin.py:115} INFO - [2024-08-28 14:41:55,198] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-08-28 14:41:55,198] {processor.py:653} WARNING - No viable dags retrieved from /home/kai/Documents/PROJETOS/twitter_extractor_airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-28 14:41:55,206] {processor.py:161} INFO - Processing /home/kai/Documents/PROJETOS/twitter_extractor_airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.023 seconds
[2024-08-28 14:42:29,472] {processor.py:153} INFO - Started process (PID=49300) to work on /home/kai/Documents/PROJETOS/twitter_extractor_airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-28 14:42:29,472] {processor.py:641} INFO - Processing file /home/kai/Documents/PROJETOS/twitter_extractor_airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-08-28 14:42:29,473] {logging_mixin.py:115} INFO - [2024-08-28 14:42:29,473] {dagbag.py:507} INFO - Filling up the DagBag from /home/kai/Documents/PROJETOS/twitter_extractor_airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-28 14:42:29,487] {logging_mixin.py:115} INFO - [2024-08-28 14:42:29,487] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/kai/Documents/PROJETOS/twitter_extractor_airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-08-28 14:42:29,487] {logging_mixin.py:115} INFO - [2024-08-28 14:42:29,487] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-08-28 14:42:29,488] {processor.py:653} WARNING - No viable dags retrieved from /home/kai/Documents/PROJETOS/twitter_extractor_airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-28 14:42:29,497] {processor.py:161} INFO - Processing /home/kai/Documents/PROJETOS/twitter_extractor_airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.028 seconds
[2024-08-28 14:43:02,088] {processor.py:153} INFO - Started process (PID=49496) to work on /home/kai/Documents/PROJETOS/twitter_extractor_airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-28 14:43:02,089] {processor.py:641} INFO - Processing file /home/kai/Documents/PROJETOS/twitter_extractor_airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-08-28 14:43:02,089] {logging_mixin.py:115} INFO - [2024-08-28 14:43:02,089] {dagbag.py:507} INFO - Filling up the DagBag from /home/kai/Documents/PROJETOS/twitter_extractor_airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-28 14:43:02,101] {logging_mixin.py:115} INFO - [2024-08-28 14:43:02,101] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/kai/Documents/PROJETOS/twitter_extractor_airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-08-28 14:43:02,101] {logging_mixin.py:115} INFO - [2024-08-28 14:43:02,101] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-08-28 14:43:02,102] {processor.py:653} WARNING - No viable dags retrieved from /home/kai/Documents/PROJETOS/twitter_extractor_airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-28 14:43:02,110] {processor.py:161} INFO - Processing /home/kai/Documents/PROJETOS/twitter_extractor_airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.025 seconds
[2024-08-28 14:43:35,891] {processor.py:153} INFO - Started process (PID=49699) to work on /home/kai/Documents/PROJETOS/twitter_extractor_airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-28 14:43:35,892] {processor.py:641} INFO - Processing file /home/kai/Documents/PROJETOS/twitter_extractor_airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-08-28 14:43:35,893] {logging_mixin.py:115} INFO - [2024-08-28 14:43:35,893] {dagbag.py:507} INFO - Filling up the DagBag from /home/kai/Documents/PROJETOS/twitter_extractor_airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-28 14:43:35,904] {logging_mixin.py:115} INFO - [2024-08-28 14:43:35,904] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/kai/Documents/PROJETOS/twitter_extractor_airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-08-28 14:43:35,904] {logging_mixin.py:115} INFO - [2024-08-28 14:43:35,904] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-08-28 14:43:35,904] {processor.py:653} WARNING - No viable dags retrieved from /home/kai/Documents/PROJETOS/twitter_extractor_airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-28 14:43:35,912] {processor.py:161} INFO - Processing /home/kai/Documents/PROJETOS/twitter_extractor_airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.023 seconds
[2024-08-28 14:44:07,862] {processor.py:153} INFO - Started process (PID=49951) to work on /home/kai/Documents/PROJETOS/twitter_extractor_airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-28 14:44:07,864] {processor.py:641} INFO - Processing file /home/kai/Documents/PROJETOS/twitter_extractor_airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-08-28 14:44:07,866] {logging_mixin.py:115} INFO - [2024-08-28 14:44:07,866] {dagbag.py:507} INFO - Filling up the DagBag from /home/kai/Documents/PROJETOS/twitter_extractor_airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-28 14:44:07,883] {logging_mixin.py:115} INFO - [2024-08-28 14:44:07,882] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/kai/Documents/PROJETOS/twitter_extractor_airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-08-28 14:44:07,883] {logging_mixin.py:115} INFO - [2024-08-28 14:44:07,883] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-08-28 14:44:07,883] {processor.py:653} WARNING - No viable dags retrieved from /home/kai/Documents/PROJETOS/twitter_extractor_airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-28 14:44:07,893] {processor.py:161} INFO - Processing /home/kai/Documents/PROJETOS/twitter_extractor_airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.035 seconds
[2024-08-28 14:44:54,178] {processor.py:153} INFO - Started process (PID=50349) to work on /home/kai/Documents/PROJETOS/twitter_extractor_airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-28 14:44:54,179] {processor.py:641} INFO - Processing file /home/kai/Documents/PROJETOS/twitter_extractor_airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-08-28 14:44:54,179] {logging_mixin.py:115} INFO - [2024-08-28 14:44:54,179] {dagbag.py:507} INFO - Filling up the DagBag from /home/kai/Documents/PROJETOS/twitter_extractor_airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-28 14:44:54,191] {logging_mixin.py:115} INFO - [2024-08-28 14:44:54,190] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/kai/Documents/PROJETOS/twitter_extractor_airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-08-28 14:44:54,191] {logging_mixin.py:115} INFO - [2024-08-28 14:44:54,191] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-08-28 14:44:54,191] {processor.py:653} WARNING - No viable dags retrieved from /home/kai/Documents/PROJETOS/twitter_extractor_airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-28 14:44:54,199] {processor.py:161} INFO - Processing /home/kai/Documents/PROJETOS/twitter_extractor_airflow/venv/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.022 seconds
[2024-08-28 16:57:34,908] {processor.py:153} INFO - Started process (PID=9728) to work on /home/kai/Documents/PROJETOS/twitter_extractor_airflow/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-28 16:57:34,910] {processor.py:641} INFO - Processing file /home/kai/Documents/PROJETOS/twitter_extractor_airflow/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-08-28 16:57:34,911] {logging_mixin.py:115} INFO - [2024-08-28 16:57:34,911] {dagbag.py:507} INFO - Filling up the DagBag from /home/kai/Documents/PROJETOS/twitter_extractor_airflow/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-28 16:57:34,925] {logging_mixin.py:115} INFO - [2024-08-28 16:57:34,924] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/kai/Documents/PROJETOS/twitter_extractor_airflow/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-08-28 16:57:34,925] {logging_mixin.py:115} INFO - [2024-08-28 16:57:34,925] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-08-28 16:57:34,925] {processor.py:653} WARNING - No viable dags retrieved from /home/kai/Documents/PROJETOS/twitter_extractor_airflow/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-28 16:57:34,933] {processor.py:161} INFO - Processing /home/kai/Documents/PROJETOS/twitter_extractor_airflow/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.027 seconds
[2024-08-28 16:58:05,580] {processor.py:153} INFO - Started process (PID=10042) to work on /home/kai/Documents/PROJETOS/twitter_extractor_airflow/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-28 16:58:05,581] {processor.py:641} INFO - Processing file /home/kai/Documents/PROJETOS/twitter_extractor_airflow/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-08-28 16:58:05,582] {logging_mixin.py:115} INFO - [2024-08-28 16:58:05,582] {dagbag.py:507} INFO - Filling up the DagBag from /home/kai/Documents/PROJETOS/twitter_extractor_airflow/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-28 16:58:05,599] {logging_mixin.py:115} INFO - [2024-08-28 16:58:05,599] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/kai/Documents/PROJETOS/twitter_extractor_airflow/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-08-28 16:58:05,600] {logging_mixin.py:115} INFO - [2024-08-28 16:58:05,600] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-08-28 16:58:05,600] {processor.py:653} WARNING - No viable dags retrieved from /home/kai/Documents/PROJETOS/twitter_extractor_airflow/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-28 16:58:05,611] {processor.py:161} INFO - Processing /home/kai/Documents/PROJETOS/twitter_extractor_airflow/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.035 seconds
[2024-08-28 16:58:38,452] {processor.py:153} INFO - Started process (PID=10143) to work on /home/kai/Documents/PROJETOS/twitter_extractor_airflow/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-28 16:58:38,452] {processor.py:641} INFO - Processing file /home/kai/Documents/PROJETOS/twitter_extractor_airflow/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-08-28 16:58:38,453] {logging_mixin.py:115} INFO - [2024-08-28 16:58:38,453] {dagbag.py:507} INFO - Filling up the DagBag from /home/kai/Documents/PROJETOS/twitter_extractor_airflow/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-28 16:58:38,465] {logging_mixin.py:115} INFO - [2024-08-28 16:58:38,465] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/kai/Documents/PROJETOS/twitter_extractor_airflow/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-08-28 16:58:38,465] {logging_mixin.py:115} INFO - [2024-08-28 16:58:38,465] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-08-28 16:58:38,465] {processor.py:653} WARNING - No viable dags retrieved from /home/kai/Documents/PROJETOS/twitter_extractor_airflow/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-28 16:58:38,476] {processor.py:161} INFO - Processing /home/kai/Documents/PROJETOS/twitter_extractor_airflow/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.027 seconds
[2024-08-28 16:59:12,188] {processor.py:153} INFO - Started process (PID=10542) to work on /home/kai/Documents/PROJETOS/twitter_extractor_airflow/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-28 16:59:12,188] {processor.py:641} INFO - Processing file /home/kai/Documents/PROJETOS/twitter_extractor_airflow/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-08-28 16:59:12,189] {logging_mixin.py:115} INFO - [2024-08-28 16:59:12,188] {dagbag.py:507} INFO - Filling up the DagBag from /home/kai/Documents/PROJETOS/twitter_extractor_airflow/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-28 16:59:12,201] {logging_mixin.py:115} INFO - [2024-08-28 16:59:12,201] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/kai/Documents/PROJETOS/twitter_extractor_airflow/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-08-28 16:59:12,201] {logging_mixin.py:115} INFO - [2024-08-28 16:59:12,201] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-08-28 16:59:12,201] {processor.py:653} WARNING - No viable dags retrieved from /home/kai/Documents/PROJETOS/twitter_extractor_airflow/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-28 16:59:12,208] {processor.py:161} INFO - Processing /home/kai/Documents/PROJETOS/twitter_extractor_airflow/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.023 seconds
[2024-08-28 16:59:44,709] {processor.py:153} INFO - Started process (PID=10928) to work on /home/kai/Documents/PROJETOS/twitter_extractor_airflow/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-28 16:59:44,710] {processor.py:641} INFO - Processing file /home/kai/Documents/PROJETOS/twitter_extractor_airflow/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-08-28 16:59:44,710] {logging_mixin.py:115} INFO - [2024-08-28 16:59:44,710] {dagbag.py:507} INFO - Filling up the DagBag from /home/kai/Documents/PROJETOS/twitter_extractor_airflow/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-28 16:59:44,722] {logging_mixin.py:115} INFO - [2024-08-28 16:59:44,721] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/kai/Documents/PROJETOS/twitter_extractor_airflow/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-08-28 16:59:44,722] {logging_mixin.py:115} INFO - [2024-08-28 16:59:44,722] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-08-28 16:59:44,722] {processor.py:653} WARNING - No viable dags retrieved from /home/kai/Documents/PROJETOS/twitter_extractor_airflow/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-28 16:59:44,730] {processor.py:161} INFO - Processing /home/kai/Documents/PROJETOS/twitter_extractor_airflow/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.023 seconds
[2024-08-28 17:00:17,724] {processor.py:153} INFO - Started process (PID=11097) to work on /home/kai/Documents/PROJETOS/twitter_extractor_airflow/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-28 17:00:17,724] {processor.py:641} INFO - Processing file /home/kai/Documents/PROJETOS/twitter_extractor_airflow/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-08-28 17:00:17,725] {logging_mixin.py:115} INFO - [2024-08-28 17:00:17,725] {dagbag.py:507} INFO - Filling up the DagBag from /home/kai/Documents/PROJETOS/twitter_extractor_airflow/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-28 17:00:17,736] {logging_mixin.py:115} INFO - [2024-08-28 17:00:17,736] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/kai/Documents/PROJETOS/twitter_extractor_airflow/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-08-28 17:00:17,736] {logging_mixin.py:115} INFO - [2024-08-28 17:00:17,736] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-08-28 17:00:17,736] {processor.py:653} WARNING - No viable dags retrieved from /home/kai/Documents/PROJETOS/twitter_extractor_airflow/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-28 17:00:17,744] {processor.py:161} INFO - Processing /home/kai/Documents/PROJETOS/twitter_extractor_airflow/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.023 seconds
[2024-08-28 17:00:52,402] {processor.py:153} INFO - Started process (PID=11311) to work on /home/kai/Documents/PROJETOS/twitter_extractor_airflow/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-28 17:00:52,403] {processor.py:641} INFO - Processing file /home/kai/Documents/PROJETOS/twitter_extractor_airflow/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-08-28 17:00:52,404] {logging_mixin.py:115} INFO - [2024-08-28 17:00:52,404] {dagbag.py:507} INFO - Filling up the DagBag from /home/kai/Documents/PROJETOS/twitter_extractor_airflow/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-28 17:00:52,415] {logging_mixin.py:115} INFO - [2024-08-28 17:00:52,415] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/kai/Documents/PROJETOS/twitter_extractor_airflow/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-08-28 17:00:52,416] {logging_mixin.py:115} INFO - [2024-08-28 17:00:52,416] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-08-28 17:00:52,416] {processor.py:653} WARNING - No viable dags retrieved from /home/kai/Documents/PROJETOS/twitter_extractor_airflow/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-28 17:00:52,424] {processor.py:161} INFO - Processing /home/kai/Documents/PROJETOS/twitter_extractor_airflow/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.025 seconds
[2024-08-28 17:01:22,763] {processor.py:153} INFO - Started process (PID=11475) to work on /home/kai/Documents/PROJETOS/twitter_extractor_airflow/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-28 17:01:22,765] {processor.py:641} INFO - Processing file /home/kai/Documents/PROJETOS/twitter_extractor_airflow/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-08-28 17:01:22,765] {logging_mixin.py:115} INFO - [2024-08-28 17:01:22,765] {dagbag.py:507} INFO - Filling up the DagBag from /home/kai/Documents/PROJETOS/twitter_extractor_airflow/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-28 17:01:22,780] {logging_mixin.py:115} INFO - [2024-08-28 17:01:22,780] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/kai/Documents/PROJETOS/twitter_extractor_airflow/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-08-28 17:01:22,780] {logging_mixin.py:115} INFO - [2024-08-28 17:01:22,780] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-08-28 17:01:22,780] {processor.py:653} WARNING - No viable dags retrieved from /home/kai/Documents/PROJETOS/twitter_extractor_airflow/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-28 17:01:22,791] {processor.py:161} INFO - Processing /home/kai/Documents/PROJETOS/twitter_extractor_airflow/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.031 seconds
[2024-08-28 17:01:56,289] {processor.py:153} INFO - Started process (PID=11647) to work on /home/kai/Documents/PROJETOS/twitter_extractor_airflow/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-28 17:01:56,290] {processor.py:641} INFO - Processing file /home/kai/Documents/PROJETOS/twitter_extractor_airflow/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-08-28 17:01:56,290] {logging_mixin.py:115} INFO - [2024-08-28 17:01:56,290] {dagbag.py:507} INFO - Filling up the DagBag from /home/kai/Documents/PROJETOS/twitter_extractor_airflow/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-28 17:01:56,302] {logging_mixin.py:115} INFO - [2024-08-28 17:01:56,302] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/kai/Documents/PROJETOS/twitter_extractor_airflow/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-08-28 17:01:56,302] {logging_mixin.py:115} INFO - [2024-08-28 17:01:56,302] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-08-28 17:01:56,302] {processor.py:653} WARNING - No viable dags retrieved from /home/kai/Documents/PROJETOS/twitter_extractor_airflow/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-28 17:01:56,312] {processor.py:161} INFO - Processing /home/kai/Documents/PROJETOS/twitter_extractor_airflow/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.025 seconds
[2024-08-28 17:02:27,105] {processor.py:153} INFO - Started process (PID=11968) to work on /home/kai/Documents/PROJETOS/twitter_extractor_airflow/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-28 17:02:27,105] {processor.py:641} INFO - Processing file /home/kai/Documents/PROJETOS/twitter_extractor_airflow/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-08-28 17:02:27,106] {logging_mixin.py:115} INFO - [2024-08-28 17:02:27,106] {dagbag.py:507} INFO - Filling up the DagBag from /home/kai/Documents/PROJETOS/twitter_extractor_airflow/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-28 17:02:27,119] {logging_mixin.py:115} INFO - [2024-08-28 17:02:27,119] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/kai/Documents/PROJETOS/twitter_extractor_airflow/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-08-28 17:02:27,120] {logging_mixin.py:115} INFO - [2024-08-28 17:02:27,120] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-08-28 17:02:27,120] {processor.py:653} WARNING - No viable dags retrieved from /home/kai/Documents/PROJETOS/twitter_extractor_airflow/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-28 17:02:27,130] {processor.py:161} INFO - Processing /home/kai/Documents/PROJETOS/twitter_extractor_airflow/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.028 seconds
[2024-08-28 17:02:59,105] {processor.py:153} INFO - Started process (PID=12215) to work on /home/kai/Documents/PROJETOS/twitter_extractor_airflow/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-28 17:02:59,106] {processor.py:641} INFO - Processing file /home/kai/Documents/PROJETOS/twitter_extractor_airflow/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-08-28 17:02:59,107] {logging_mixin.py:115} INFO - [2024-08-28 17:02:59,106] {dagbag.py:507} INFO - Filling up the DagBag from /home/kai/Documents/PROJETOS/twitter_extractor_airflow/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-28 17:02:59,118] {logging_mixin.py:115} INFO - [2024-08-28 17:02:59,118] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/kai/Documents/PROJETOS/twitter_extractor_airflow/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-08-28 17:02:59,119] {logging_mixin.py:115} INFO - [2024-08-28 17:02:59,119] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-08-28 17:02:59,119] {processor.py:653} WARNING - No viable dags retrieved from /home/kai/Documents/PROJETOS/twitter_extractor_airflow/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-28 17:02:59,127] {processor.py:161} INFO - Processing /home/kai/Documents/PROJETOS/twitter_extractor_airflow/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.025 seconds
[2024-08-28 17:03:31,535] {processor.py:153} INFO - Started process (PID=12396) to work on /home/kai/Documents/PROJETOS/twitter_extractor_airflow/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-28 17:03:31,536] {processor.py:641} INFO - Processing file /home/kai/Documents/PROJETOS/twitter_extractor_airflow/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-08-28 17:03:31,537] {logging_mixin.py:115} INFO - [2024-08-28 17:03:31,537] {dagbag.py:507} INFO - Filling up the DagBag from /home/kai/Documents/PROJETOS/twitter_extractor_airflow/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-28 17:03:31,550] {logging_mixin.py:115} INFO - [2024-08-28 17:03:31,549] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/kai/Documents/PROJETOS/twitter_extractor_airflow/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-08-28 17:03:31,550] {logging_mixin.py:115} INFO - [2024-08-28 17:03:31,550] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-08-28 17:03:31,550] {processor.py:653} WARNING - No viable dags retrieved from /home/kai/Documents/PROJETOS/twitter_extractor_airflow/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-28 17:03:31,559] {processor.py:161} INFO - Processing /home/kai/Documents/PROJETOS/twitter_extractor_airflow/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.026 seconds
[2024-08-28 17:04:03,496] {processor.py:153} INFO - Started process (PID=12436) to work on /home/kai/Documents/PROJETOS/twitter_extractor_airflow/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-28 17:04:03,497] {processor.py:641} INFO - Processing file /home/kai/Documents/PROJETOS/twitter_extractor_airflow/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-08-28 17:04:03,497] {logging_mixin.py:115} INFO - [2024-08-28 17:04:03,497] {dagbag.py:507} INFO - Filling up the DagBag from /home/kai/Documents/PROJETOS/twitter_extractor_airflow/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-28 17:04:03,509] {logging_mixin.py:115} INFO - [2024-08-28 17:04:03,509] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/kai/Documents/PROJETOS/twitter_extractor_airflow/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-08-28 17:04:03,509] {logging_mixin.py:115} INFO - [2024-08-28 17:04:03,509] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-08-28 17:04:03,509] {processor.py:653} WARNING - No viable dags retrieved from /home/kai/Documents/PROJETOS/twitter_extractor_airflow/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-28 17:04:03,517] {processor.py:161} INFO - Processing /home/kai/Documents/PROJETOS/twitter_extractor_airflow/venv/lib/python3.9/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.024 seconds
[2024-08-28 17:04:40,217] {processor.py:153} INFO - Started process (PID=12691) to work on /home/kai/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-28 17:04:40,217] {processor.py:641} INFO - Processing file /home/kai/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-08-28 17:04:40,218] {logging_mixin.py:115} INFO - [2024-08-28 17:04:40,218] {dagbag.py:507} INFO - Filling up the DagBag from /home/kai/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-28 17:04:40,229] {logging_mixin.py:115} INFO - [2024-08-28 17:04:40,229] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/kai/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-08-28 17:04:40,229] {logging_mixin.py:115} INFO - [2024-08-28 17:04:40,229] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-08-28 17:04:40,230] {processor.py:653} WARNING - No viable dags retrieved from /home/kai/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-28 17:04:40,237] {processor.py:161} INFO - Processing /home/kai/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.023 seconds
[2024-08-28 17:05:12,575] {processor.py:153} INFO - Started process (PID=12800) to work on /home/kai/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-28 17:05:12,576] {processor.py:641} INFO - Processing file /home/kai/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-08-28 17:05:12,576] {logging_mixin.py:115} INFO - [2024-08-28 17:05:12,576] {dagbag.py:507} INFO - Filling up the DagBag from /home/kai/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-28 17:05:12,587] {logging_mixin.py:115} INFO - [2024-08-28 17:05:12,587] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/kai/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-08-28 17:05:12,587] {logging_mixin.py:115} INFO - [2024-08-28 17:05:12,587] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-08-28 17:05:12,587] {processor.py:653} WARNING - No viable dags retrieved from /home/kai/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-28 17:05:12,595] {processor.py:161} INFO - Processing /home/kai/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.022 seconds
[2024-08-28 17:05:45,647] {processor.py:153} INFO - Started process (PID=13022) to work on /home/kai/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-28 17:05:45,648] {processor.py:641} INFO - Processing file /home/kai/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-08-28 17:05:45,648] {logging_mixin.py:115} INFO - [2024-08-28 17:05:45,648] {dagbag.py:507} INFO - Filling up the DagBag from /home/kai/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-28 17:05:45,659] {logging_mixin.py:115} INFO - [2024-08-28 17:05:45,658] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/kai/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-08-28 17:05:45,659] {logging_mixin.py:115} INFO - [2024-08-28 17:05:45,659] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-08-28 17:05:45,659] {processor.py:653} WARNING - No viable dags retrieved from /home/kai/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-28 17:05:45,667] {processor.py:161} INFO - Processing /home/kai/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.023 seconds
[2024-08-28 17:06:19,271] {processor.py:153} INFO - Started process (PID=13100) to work on /home/kai/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-28 17:06:19,272] {processor.py:641} INFO - Processing file /home/kai/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-08-28 17:06:19,273] {logging_mixin.py:115} INFO - [2024-08-28 17:06:19,273] {dagbag.py:507} INFO - Filling up the DagBag from /home/kai/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-28 17:06:19,283] {logging_mixin.py:115} INFO - [2024-08-28 17:06:19,283] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/kai/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-08-28 17:06:19,284] {logging_mixin.py:115} INFO - [2024-08-28 17:06:19,284] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-08-28 17:06:19,284] {processor.py:653} WARNING - No viable dags retrieved from /home/kai/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-28 17:06:19,291] {processor.py:161} INFO - Processing /home/kai/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.022 seconds
[2024-08-28 17:06:51,432] {processor.py:153} INFO - Started process (PID=13253) to work on /home/kai/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-28 17:06:51,433] {processor.py:641} INFO - Processing file /home/kai/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-08-28 17:06:51,433] {logging_mixin.py:115} INFO - [2024-08-28 17:06:51,433] {dagbag.py:507} INFO - Filling up the DagBag from /home/kai/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-28 17:06:51,449] {logging_mixin.py:115} INFO - [2024-08-28 17:06:51,448] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/kai/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-08-28 17:06:51,449] {logging_mixin.py:115} INFO - [2024-08-28 17:06:51,449] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-08-28 17:06:51,449] {processor.py:653} WARNING - No viable dags retrieved from /home/kai/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-28 17:06:51,462] {processor.py:161} INFO - Processing /home/kai/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.035 seconds
[2024-08-28 17:07:25,106] {processor.py:153} INFO - Started process (PID=13507) to work on /home/kai/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-28 17:07:25,107] {processor.py:641} INFO - Processing file /home/kai/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-08-28 17:07:25,108] {logging_mixin.py:115} INFO - [2024-08-28 17:07:25,108] {dagbag.py:507} INFO - Filling up the DagBag from /home/kai/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-28 17:07:25,119] {logging_mixin.py:115} INFO - [2024-08-28 17:07:25,118] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/kai/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-08-28 17:07:25,119] {logging_mixin.py:115} INFO - [2024-08-28 17:07:25,119] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-08-28 17:07:25,119] {processor.py:653} WARNING - No viable dags retrieved from /home/kai/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-28 17:07:25,127] {processor.py:161} INFO - Processing /home/kai/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.024 seconds
[2024-08-28 17:07:57,082] {processor.py:153} INFO - Started process (PID=13564) to work on /home/kai/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-28 17:07:57,083] {processor.py:641} INFO - Processing file /home/kai/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-08-28 17:07:57,083] {logging_mixin.py:115} INFO - [2024-08-28 17:07:57,083] {dagbag.py:507} INFO - Filling up the DagBag from /home/kai/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-28 17:07:57,094] {logging_mixin.py:115} INFO - [2024-08-28 17:07:57,094] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/kai/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-08-28 17:07:57,094] {logging_mixin.py:115} INFO - [2024-08-28 17:07:57,094] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-08-28 17:07:57,094] {processor.py:653} WARNING - No viable dags retrieved from /home/kai/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-28 17:07:57,102] {processor.py:161} INFO - Processing /home/kai/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.023 seconds
[2024-08-28 17:08:31,925] {processor.py:153} INFO - Started process (PID=13603) to work on /home/kai/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-28 17:08:31,925] {processor.py:641} INFO - Processing file /home/kai/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-08-28 17:08:31,926] {logging_mixin.py:115} INFO - [2024-08-28 17:08:31,926] {dagbag.py:507} INFO - Filling up the DagBag from /home/kai/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-28 17:08:31,938] {logging_mixin.py:115} INFO - [2024-08-28 17:08:31,937] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/kai/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-08-28 17:08:31,938] {logging_mixin.py:115} INFO - [2024-08-28 17:08:31,938] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-08-28 17:08:31,938] {processor.py:653} WARNING - No viable dags retrieved from /home/kai/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-28 17:08:31,947] {processor.py:161} INFO - Processing /home/kai/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.024 seconds
[2024-08-28 17:09:03,806] {processor.py:153} INFO - Started process (PID=13643) to work on /home/kai/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-28 17:09:03,807] {processor.py:641} INFO - Processing file /home/kai/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-08-28 17:09:03,807] {logging_mixin.py:115} INFO - [2024-08-28 17:09:03,807] {dagbag.py:507} INFO - Filling up the DagBag from /home/kai/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-28 17:09:03,830] {logging_mixin.py:115} INFO - [2024-08-28 17:09:03,829] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/kai/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-08-28 17:09:03,830] {logging_mixin.py:115} INFO - [2024-08-28 17:09:03,830] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-08-28 17:09:03,830] {processor.py:653} WARNING - No viable dags retrieved from /home/kai/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-28 17:09:03,840] {processor.py:161} INFO - Processing /home/kai/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.036 seconds
[2024-08-28 17:09:36,614] {processor.py:153} INFO - Started process (PID=13733) to work on /home/kai/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-28 17:09:36,615] {processor.py:641} INFO - Processing file /home/kai/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-08-28 17:09:36,615] {logging_mixin.py:115} INFO - [2024-08-28 17:09:36,615] {dagbag.py:507} INFO - Filling up the DagBag from /home/kai/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-28 17:09:36,627] {logging_mixin.py:115} INFO - [2024-08-28 17:09:36,626] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/kai/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-08-28 17:09:36,627] {logging_mixin.py:115} INFO - [2024-08-28 17:09:36,627] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-08-28 17:09:36,627] {processor.py:653} WARNING - No viable dags retrieved from /home/kai/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-28 17:09:36,635] {processor.py:161} INFO - Processing /home/kai/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.023 seconds
[2024-08-28 17:10:09,265] {processor.py:153} INFO - Started process (PID=13771) to work on /home/kai/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-28 17:10:09,265] {processor.py:641} INFO - Processing file /home/kai/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-08-28 17:10:09,266] {logging_mixin.py:115} INFO - [2024-08-28 17:10:09,266] {dagbag.py:507} INFO - Filling up the DagBag from /home/kai/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-28 17:10:09,277] {logging_mixin.py:115} INFO - [2024-08-28 17:10:09,276] {example_local_kubernetes_executor.py:37} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/kai/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 35, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-08-28 17:10:09,277] {logging_mixin.py:115} INFO - [2024-08-28 17:10:09,277] {example_local_kubernetes_executor.py:38} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-08-28 17:10:09,277] {processor.py:653} WARNING - No viable dags retrieved from /home/kai/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-08-28 17:10:09,285] {processor.py:161} INFO - Processing /home/kai/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.024 seconds
